title: devlog
description: Building in public. Weekly field notes from a semester-long engineering project.
baseurl: "/JVC-webpage"
url: "https://dvdjnt.gitlab.io"

# Build
permalink: /week-updates/:year-:month-:day-:slug/

# Exclude from build output
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitlab-ci.yml
